name: Lint Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # remove before node_modules
      - name: Remove node_modules & package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      # Install packages
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run ESLint
      - name: Run ESLint
        run: npm run lint-cicd
